### ISSUE TITLE
Nullptr dereference when generating proto map value

### ISSUE THREAD

**Issue by dmcardle** [google/libprotobuf-mutator#184]
I tried fuzzing a proto containing that contains a `map<>`, but ran into a segfault ([original thread](https://chromium-review.googlesource.com/c/chromium/src/+/2418987/1/testing/libfuzzer/proto/json.proto#19) on a Chromium CL.)  

I'm including a stack trace  that I saw while working on [this CL](https://chromium-review.googlesource.com/c/chromium/src/+/2419009/1). I can make a more minimal example if you'd like, but I believe the key part is that the proto contains a map.

```
Thread 1 "test_json_conve" received signal SIGSEGV, Segmentation fault.
json_proto::JsonValue::IsInitialized (this=0x0) at gen/testing/libfuzzer/proto/json.pb.cc:1332
1332      switch (value_case()) {
(gdb) bt
#0  json_proto::JsonValue::IsInitialized (this=0x0) at gen/testing/libfuzzer/proto/json.pb.cc:1332
#1  0x5692cd4f in google::protobuf::internal::MapTypeHandler<(google::protobuf::internal::WireFormatLite::FieldType)11, json_proto::JsonValue>::IsInitialized (value=0x0)
    at ../../third_party/protobuf/src/google/protobuf/map_type_handler.h:636
#2  google::protobuf::internal::MapEntryImpl<json_proto::JsonObject_PairsEntry_DoNotUse, google::protobuf::Message, std::__Cr::basic_string<char, std::__Cr::char_traits<char>, std::__Cr::allocator<char> >, json_proto::JsonValue, (google::protobuf::internal::WireFormatLite::FieldType)9, (google::protobuf::internal::WireFormatLite::FieldType)11, 0>::IsInitialized
    (this=0xef12d370) at ../../third_party/protobuf/src/google/protobuf/map_entry_lite.h:353
#3  0x567e0dc3 in protobuf_mutator::Mutator::Mutate (this=0xffffa1b8, message=0xef12d370, size_increase_hint=1016) at ../../third_party/libprotobuf-mutator/src/src/mutator.cc:488
#4  0x567e64b2 in protobuf_mutator::FieldMutator::Mutate (this=<optimized out>, message=0xffff95b8) at ../../third_party/libprotobuf-mutator/src/src/mutator.cc:397
#5  protobuf_mutator::(anonymous namespace)::CreateField::ForType<std::__Cr::unique_ptr<google::protobuf::Message, std::__Cr::default_delete<google::protobuf::Message> > > (
    this=<optimized out>, field=..., size_increase_hint=<optimized out>, mutator=0xffffa1b8) at ../../third_party/libprotobuf-mutator/src/src/mutator.cc:445
#6  0x567e04a7 in protobuf_mutator::FieldFunction<protobuf_mutator::(anonymous namespace)::CreateField, void>::operator()<protobuf_mutator::FieldInstance, unsigned int, protobuf_mutator::Mutator*> (this=<optimized out>, field=..., args=<optimized out>, args=<optimized out>) at ../../third_party/libprotobuf-mutator/src/src/field_instance.h:439
#7  protobuf_mutator::Mutator::Mutate (this=0xffffa1b8, message=0xefb02940, size_increase_hint=2032) at ../../third_party/libprotobuf-mutator/src/src/mutator.cc:463
#8  0x567e64b2 in protobuf_mutator::FieldMutator::Mutate (this=<optimized out>, message=0xffff96e8) at ../../third_party/libprotobuf-mutator/src/src/mutator.cc:397
#9  protobuf_mutator::(anonymous namespace)::CreateField::ForType<std::__Cr::unique_ptr<google::protobuf::Message, std::__Cr::default_delete<google::protobuf::Message> > > (
    this=<optimized out>, field=..., size_increase_hint=<optimized out>, mutator=0xffffa1b8) at ../../third_party/libprotobuf-mutator/src/src/mutator.cc:445
#10 0x567e04a7 in protobuf_mutator::FieldFunction<protobuf_mutator::(anonymous namespace)::CreateField, void>::operator()<protobuf_mutator::FieldInstance, unsigned int, protobuf_mutator::Mutator*> (this=<optimized out>, field=..., args=<optimized out>, args=<optimized out>) at ../../third_party/libprotobuf-mutator/src/src/field_instance.h:439
#11 protobuf_mutator::Mutator::Mutate (this=0xffffa1b8, message=0xf07d3090, size_increase_hint=4064) at ../../third_party/libprotobuf-mutator/src/src/mutator.cc:463
#12 0x567df600 in protobuf_mutator::libfuzzer::(anonymous namespace)::MutateMessage (seed=<optimized out>, input=..., output=0xffffa200, message=0xf07d3090)
    at ../../third_party/libprotobuf-mutator/src/src/libfuzzer/libfuzzer_macro.cc:97
#13 0x567df331 in protobuf_mutator::libfuzzer::(anonymous namespace)::MutateTextMessage (
    data=0xeb902900 "boolean_value {\n  value: true\n}\nean_value {\n      value: false\n    }\n  }\n}\ne {\\n}\\n\"\n    }\n  }\n}\n_value {\n      value: \"\\001\\000\"\n    }\n  }\n}\n", '\276' <repeats 58 times>..., size=32, max_size=4096, seed=1353339904, message=0xf07d3090) at ../../third_party/libprotobuf-mutator/src/src/libfuzzer/libfuzzer_macro.cc:127
#14 0x567df277 in protobuf_mutator::libfuzzer::CustomProtoMutator (binary=<optimized out>,
    data=0xeb902900 "boolean_value {\n  value: true\n}\nean_value {\n      value: false\n    }\n  }\n}\ne {\\n}\\n\"\n    }\n  }\n}\n_value {\n      value: \"\\001\\000\"\n    }\n  }\n}\n", '\276' <repeats 58 times>..., size=32, max_size=4096, seed=1353339904, input=0xf07d3090) at ../../third_party/libprotobuf-mutator/src/src/libfuzzer/libfuzzer_macro.cc:165
#15 0x567c694c in LLVMFuzzerCustomMutator (
    data=0xeb902900 "boolean_value {\n  value: true\n}\nean_value {\n      value: false\n    }\n  }\n}\ne {\\n}\\n\"\n    }\n  }\n}\n_value {\n      value: \"\\001\\000\"\n    }\n  }\n}\n", '\276' <repeats 58 times>..., size=32, max_size=4096, seed=1353339904) at ../../testing/libfuzzer/fuzzers/json_fuzzer.cc:59
#16 0x568f490b in fuzzer::MutationDispatcher::Mutate_Custom (this=0xedf3e800,
    Data=0xeb902900 "boolean_value {\n  value: true\n}\nean_value {\n      value: false\n    }\n  }\n}\ne {\\n}\\n\"\n    }\n  }\n}\n_value {\n      value: \"\\001\\000\"\n    }\n  }\n}\n", '\276' <repeats 58 times>..., Size=32, MaxSize=4096) at ../../third_party/libFuzzer/src/FuzzerMutate.cpp:70
#17 0x568f7e00 in fuzzer::MutationDispatcher::MutateImpl (this=0xedf3e800,
    Data=0xeb902900 "boolean_value {\n  value: true\n}\nean_value {\n      value: false\n    }\n  }\n}\ne {\\n}\\n\"\n    }\n  }\n}\n_value {\n      value: \"\\001\\000\"\n    }\n  }\n}\n", '\276' <repeats 58 times>..., Size=32, MaxSize=4096, Mutators=...) at ../../third_party/libFuzzer/src/FuzzerMutate.cpp:516
#18 0x568f7ac5 in fuzzer::MutationDispatcher::Mutate (this=0xedf3e800,
    Data=0xeb902900 "boolean_value {\n  value: true\n}\nean_value {\n      value: false\n    }\n  }\n}\ne {\\n}\\n\"\n    }\n  }\n}\n_value {\n      value: \"\\001\\000\"\n    }\n  }\n}\n", '\276' <repeats 58 times>..., Size=32, MaxSize=4096) at ../../third_party/libFuzzer/src/FuzzerMutate.cpp:498
#19 0x5689dccf in fuzzer::Fuzzer::MutateAndTestOne (this=0xef503000) at ../../third_party/libFuzzer/src/FuzzerLoop.cpp:691
#20 0x568a1261 in fuzzer::Fuzzer::Loop (this=0xef503000, CorporaFiles=...) at ../../third_party/libFuzzer/src/FuzzerLoop.cpp:830
#21 0x5684013d in fuzzer::FuzzerDriver (argc=0xf066c490, argv=0xf066c4a0, Callback=0x567c6d60 <LLVMFuzzerTestOneInput(uint8_t const*, size_t)>)
    at ../../third_party/libFuzzer/src/FuzzerDriver.cpp:824
#22 0x568cecb1 in main (argc=1, argv=0xffffad54) at ../../third_party/libFuzzer/src/FuzzerMain.cpp:19
```

Note: Chromium seems to be using an oldish version of LPM (439e81f8f4847ec6e2bf11b3aa634a5d8485633d from 2019-01).

**Comment by dmcardle** [comment]
This seems to be resolved as of 8942a9ba43d8bb196230c321d46d6a137957a719. I'm updating chromium's dependency on this project in https://crrev.com/c/2427157.
